# file: monit/tasks/main.yml

- name: Monit | Make sure monit is installed
  apt:
    pkg: monit
    state: present

- name: Monit | Update the monit configuration (/etc/monit/monitrc)
  template:
    src: "etc_monit_monitrc.j2"
    dest: "/etc/monit/monitrc"
  notify:
    - restart monit

- name: Monit | Copy the sshd/ntp/chron monit service files
  template:
    src: "etc_monit_conf.d_{{item}}.j2"
    dest: "/etc/monit/conf.d/{{item}}"
  with_items:
    - sshd
    - cron
    - ntp
  notify:
    - reload monit

- name: Monit | Determine queued messages
  command: "ls -1 {{monit_eventqueue_directory}}/"
  register: monit_queued_messages
  when: not monit_email_enable or not monit_eventqueue_enable
  changed_when: False

- name: Monit | Remove queued messages
  file:
    path: "{{monit_eventqueue_directory}}/{{item}}"
    state: absent
  when: not monit_email_enable or not monit_eventqueue_enable
  with_items: monit_queued_messages.stdout_lines
