# file: monit/tasks/main.yml

- name: Monit | Make sure monit is installed
  apt:
    pkg: monit
    state: present

- name: Monit | Update the monit configuration (/etc/monit/monitrc)
  template:
    src: "etc/monit/monitrc.j2"
    dest: "/etc/monit/monitrc"
    mode: 0400
  notify:
    - restart monit

- name: Monit | Copy the sshd monit service files
  template:
    src: "etc/monit/conf.d/{{item}}.j2"
    dest: "/etc/monit/conf.d/{{item}}"
  with_items:
    - sshd
    - cron
    - ntp
  notify:
    - reload monit

- name: Create configs
  template:
    src: "etc/monit/conf.d/{{ item.type | default('base') }}.conf.j2"
    dest: "/etc/monit/conf.d/{{ item.type | default('base') }}_{{ item.process | default(item.pid | basename | replace('.pid', '')) }}.conf"
    owner: root
    group: root
    mode: 0644
  with_flattened:
    - "{{ monit_process_list }}"
  when: item.pid is defined and item.pid
  notify:
    - reload monit

- name: Monit | Determine queued messages
  command: "ls -1 {{monit_eventqueue_directory}}/"
  register: monit_queued_messages
  when: not monit_email_enable or not monit_eventqueue_enable
  changed_when: False

- name: Monit | Remove queued messages
  file:
    path: "{{monit_eventqueue_directory}}/{{item}}"
    state: absent
  when: not monit_email_enable or not monit_eventqueue_enable
  with_items: "{{ monit_queued_messages.stdout_lines | default([]) }}"
