# file: monit/tasks/main.yml

- name: Monit | Make sure monit is installed
  apt:
    pkg: monit
    state: present

- name: Monit | Update the monit configuration (/etc/monit/monitrc)
  template:
    src: "etc_monit_monitrc.j2"
    dest: "/etc/monit/monitrc"
  notify:
    - restart monit

- name: Monit | Copy the sshd/ntp/chron monit service files
  template:
    src: "etc_monit_conf.d_{{item}}.j2"
    dest: "/etc/monit/conf.d/{{item}}"
  with_items:
    - sshd
    - cron
    - ntp
  notify:
    - restart monit
